Car_Rental/Car_Rental/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Car_Rental.Data;
using Car_Rental.Models;

namespace Car_Rental.Controllers
{
    public class CardController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CardController(ApplicationDbContext context)
        {

            _context = context;
        }

        // GET: Card
        public async Task<IActionResult> Index()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View(await _context.Cards.ToListAsync());
        }

        // GET: Card/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Cards
                .FirstOrDefaultAsync(m => m.Cards_ID == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Card/Create
        public IActionResult Create()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View();
        }

        // POST: Card/Create
        [HttpPost]
        public void Create(int customers_ID)
        {
            

            Random r = new Random();
            int rInt = r.Next(0, 25);
            var CreateCard = new Card
            {
                Customers_ID = customers_ID,
                Cashback = rInt,
                Points = 0,
                Payment = 0,
            };
        }

        
       
    }
}

Car_Rental/Car_Rental/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Car_Rental.Data;
using Car_Rental.Models;

namespace Car_Rental.Controllers
{
    public class ContractController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContractController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contract
        public async Task<IActionResult> Index()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View(await _context.Contracts.ToListAsync());
        }

        // GET: Contract/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contracts
                .FirstOrDefaultAsync(m => m.Contracts_ID == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // GET: Contract/Create
        public IActionResult Create()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Contracts_ID,Customers_ID,Number,CreateDate,Cards_ID")] Contract contract)
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contract);
        }

        
    }
}

Car_Rental/Car_Rental/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Car_Rental.Data;
using Car_Rental.Models;

namespace Car_Rental.Controllers
{
    public class MenuController : Controller
    {
        // GET: MenuController
        public async Task<IActionResult> Index()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index","Admin");
            }
            return View();
        }
        public ActionResult Customers()
        {
           
            return View();
        }

        public ActionResult Car()
        {
            
            return View();
        }

        public ActionResult Rent()
        {
            
            return View();
        }

        public ActionResult Discount()
        {
            
            return View();
        }
        public ActionResult ServiceDate()
        {
            
            return View();
        }
        public ActionResult Contract()
        {
            return View();
        }
        public ActionResult HRMenu()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id != 4)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            // Вызываем метод SignOutAsync для очистки аутентификационных кук
            //await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            // Перенаправляем пользователя на главную страницу или на другую страницу
            CurrentAdmin.id = 0;
            return RedirectToAction("Index", "Admin");
        }
    }
}

Car_Rental/Car_Rental/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Car_Rental.Data;
using Car_Rental.Models;

namespace Car_Rental.Controllers
{
    public class RentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RentController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View(await _context.Rents.ToListAsync());
        }

     
        public IActionResult Create()
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Rent_ID,Customers_ID,Cars_ID,FirstDate,LastDate")] Rent rent)
        {
            var currUser = new CurrentAdmin();
            if (CurrentAdmin.id == 0)
            {
                return RedirectToAction("Index", "Admin");
            }
            if (ModelState.IsValid)
            {
                _context.Add(rent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rent);
        }

        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rent = await _context.Rents.FindAsync(id);
            if (rent == null)
            {
                return NotFound();
            }
            return View(rent);
        }

    }
}

Car_Rental/Car_Rental/Views/Menu/HRMenu.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Выбор функции</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: gray;
            padding: 20px;
        }

        .container {
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .option {
            padding: 10px;
            margin: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            cursor: pointer;
            background-color: #454142;
            color: white;
            font-size: 18px;
            text-decoration: none;
            display: block;
        }

            .option:hover {
                background-color: #454142;
            }

        .create-button {
            text-align: center;
            display: inline-block;
            padding: 5px 10px;
            background-color: #454142;
            color: white;
            border-radius: 5px;
            margin-top: 20px;
            margin-bottom: 20px;
            text-decoration: none;
            position: absolute;
            font-size: 2vw;
            right: 5%;
            top: 2%;
            width: 100px;
            height: 40px;
        }
    </style>
</head>
<body>
    <a class=" create-button" href="@Url.Action("Logout", "Menu")">Выйти</a>
    <div class="container">
        <a href="@Url.Action("db", "Admin")" class="option">Администраторы</a>
    </div>
</body>
</html>

Car_Rental/Car_Rental/Views/Menu/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Выбор функции</title>
    <style>
        body {
            background: url(images/background.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .create-button {
            text-align: center;
            display: inline-block;
            padding: 5px 10px;
            background-color: #454142;
            color: white;
            border-radius: 5px;
            margin-top:20px;
            margin-bottom: 20px;
            text-decoration: none;
            position:absolute;
            font-size:2vw;
            right:5%;
            top: 2%;
            width:100px;
            height: 40px;   
        }

        .container {
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .option {
            padding: 10px;
            margin: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            cursor: pointer;
            background-color: #454142;
            color: white;
            font-size: 18px;
            text-decoration: none;
            display: block;
        }

            .option:hover {
                background-color: #454142;
            }
    </style>
</head>
<body>
    <a class =" create-button" href="@Url.Action("Logout", "Menu")">Выйти</a>
    <div class="container">
        <h2>Выберите функцию</h2>
        <a href="@Url.Action("Index", "Order")" class="option">Создать заказ</a>
        <a href="@Url.Action("Index", "Customers")" class="option">Пользователи</a>
        <a href="@Url.Action("Index", "Car")" class="option">Автомобили</a>
        <a href="@Url.Action("Index", "Rent")" class="option">Аренды</a>
        <a href="@Url.Action("Index", "Discount")" class="option">Скидки</a>
        <a href="@Url.Action("Index", "ServiceDate")" class="option">Сервисное обслуживание</a>
        <a href="@Url.Action("Index", "Card")" class="option">Дисконтные карты</a>
        <a href="@Url.Action("Index", "Contract")" class="option">Контракты</a>
    </div>

    
</body>
</html>